#!/usr/bin/env node
/**
 * step2-auto.mjs — Mechanical step 2: AST-based import detection,
 * sibling dedup, noise strip, component wrap.
 *
 * Usage: node step2-auto.mjs <input.tsx> [--out output.tsx]
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve, basename } from "path";
import { parse } from "@babel/parser";
import _traverse from "@babel/traverse";
import _generate from "@babel/generator";
import * as t from "@babel/types";

const traverse = _traverse.default || _traverse;
const generate = _generate.default || _generate;

// Known component → import source mapping
const MEDUSA_UI = new Set(["Button", "IconButton", "Badge", "Input", "Label", "Textarea", "Select", "Table", "Avatar", "Switch", "Kbd"]);
const MEDUSA_ICONS = new Set(["Funnel", "CalendarMini", "Adjustments", "DescendingSorting", "EllipsisHorizontal", "XMark", "MagnifyingGlass", "PlusMini", "Check",
  "SquareGreySolid", "SquareBlueSolid", "SquareOrangeSolid", "SquareGreenSolid", "SquarePurpleSolid", "SquareRedSolid"]);
const LOCAL_COMPONENTS = { "ColorAvatar": "@/components/ColorAvatar" };

function step2Auto(code, name) {
  const ast = parse(code, { sourceType: "module", plugins: ["jsx", "typescript"] });

  // 1. Scan for used JSX identifiers
  const usedComponents = new Set();
  traverse(ast, {
    JSXIdentifier(path) {
      const n = path.node.name;
      if (n[0] === n[0].toUpperCase() && n !== "Fragment") usedComponents.add(n.split(".")[0]);
    },
    noScope: true,
  });

  // 2. Noise strip — context-aware
  traverse(ast, {
    JSXAttribute(path) {
      if (path.node.name?.name !== "className" || !t.isStringLiteral(path.node.value)) return;
      const cls = path.node.value.value;
      const classes = cls.split(" ");
      const cleaned = classes.filter(c => {
        if (c === "content-stretch") return false;
        if (c === "[word-break:break-word]") return false;
        if (c === "whitespace-nowrap") return false;
        return true;
      });
      // Strip relative only if no absolute children
      const parent = path.parentPath?.parentPath;
      if (parent?.node && t.isJSXElement(parent.node)) {
        const hasAbsoluteChild = parent.node.children?.some(child => {
          if (!t.isJSXElement(child)) return false;
          const childCls = child.openingElement.attributes?.find(a =>
            t.isJSXAttribute(a) && a.name?.name === "className" && t.isStringLiteral(a.value)
          );
          return childCls && childCls.value.value.includes("absolute");
        });
        if (!hasAbsoluteChild) {
          const idx = cleaned.indexOf("relative");
          if (idx !== -1) cleaned.splice(idx, 1);
        }
      }
      if (cleaned.length === 0) { path.remove(); return; }
      if (cleaned.length !== classes.length) {
        path.node.value = t.stringLiteral(cleaned.join(" "));
      }
    },
    noScope: true,
  });

  // 3. Generate output
  let output = generate(ast, { retainLines: false, compact: false }).code;

  // 4. Build imports
  const imports = [];
  const uiImports = [...usedComponents].filter(c => MEDUSA_UI.has(c));
  const iconImports = [...usedComponents].filter(c => MEDUSA_ICONS.has(c));
  const localImports = [...usedComponents].filter(c => LOCAL_COMPONENTS[c]);

  if (uiImports.length) imports.push(`import { ${uiImports.sort().join(", ")} } from "@medusajs/ui";`);
  if (iconImports.length) imports.push(`import { ${iconImports.sort().join(", ")} } from "@medusajs/icons";`);
  for (const c of localImports) imports.push(`import { ${c} } from "${LOCAL_COMPONENTS[c]}";`);

  // 5. Wrap with "use client" + imports + source comment
  const pascalName = name.replace(/-(\w)/g, (_, c) => c.toUpperCase()).replace(/^(\w)/, (_, c) => c.toUpperCase());

  // Strip existing export default + function wrapper if present
  output = output.replace(/export default function \w+\(\)\s*\{/, `export function ${pascalName}() {`);

  const header = [
    `"use client";`,
    ``,
    `// source: artifacts/transformed/${name}.tsx`,
    `// step 2: auto-generated by step2-auto.mjs`,
    ``,
    ...imports,
    ``,
  ].join("\n");

  return header + output;
}

// CLI
const args = process.argv.slice(2);
const inputFile = args.find(a => !a.startsWith("--"));
const outIdx = args.indexOf("--out");
const outputFile = outIdx !== -1 ? args[outIdx + 1] : null;

if (!inputFile) { console.log("Usage: node step2-auto.mjs <input.tsx> [--out output.tsx]"); process.exit(1); }

const name = basename(inputFile, ".tsx");
const input = readFileSync(resolve(process.cwd(), inputFile), "utf8");
const output = step2Auto(input, name);

if (outputFile) {
  writeFileSync(resolve(process.cwd(), outputFile), output);
  console.log(`Written: ${outputFile}`);
} else {
  console.log(output);
}
