<div className="bg-ui-bg-subtle flex items-start relative w-full h-full">
  <div className="bg-ui-bg-subtle flex flex-1 flex-col h-full items-center min-w-[1px] relative">
    <div className="flex flex-1 flex-col items-center min-h-[1px] relative w-full">
      <div className="flex flex-col items-center justify-center p-3 relative shrink-0 w-full">
        <div className="flex gap-3 items-center pl-0.5 pr-2 py-0.5 relative rounded-md shrink-0 w-full">
          <ColorAvatar member={member} size="xsmall" />
          <p className="flex-1 min-w-[1px] relative text-ui-fg-base txt-compact-small-plus">
            SuperTasks
          </p>
          <EllipsisHorizontal className="w-[15px] h-[15px]" />
        </div>
      </div>
      <div className="flex flex-col items-center justify-center overflow-clip px-3 relative shrink-0 w-full">
        <div className="flex gap-[3px] items-center justify-center overflow-clip relative shrink-0 w-full">
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
          <div className="bg-ui-border-strong relative shrink-0 size-px" />
        </div>
      </div>
      <div className="flex flex-col isolate pb-3 pt-8 px-3 relative shrink-0 w-full">
        <div className="bg-ui-bg-subtle-pressed flex gap-3 h-9 items-center overflow-clip px-2 py-1 relative rounded-md shrink-0 w-full z-[7]">
          <ChartBar className="w-[15px] h-[15px]" />
          <p className="flex-1 min-w-[1px] relative text-ui-fg-base txt-compact-small-plus">
            Dashboard
          </p>
        </div>
        <div className="flex gap-3 h-9 items-center overflow-clip px-2 py-1 relative rounded-md shrink-0 w-full z-[6]">
          <ListCheckbox className="w-[15px] h-[15px]" />
          <p className="flex-1 min-w-[1px] relative text-ui-fg-subtle txt-compact-small-plus">
            Tasks
          </p>
        </div>
        <div className="flex gap-3 h-9 items-center overflow-clip px-2 py-1 relative rounded-md shrink-0 w-full z-[5]">
          <Users className="w-[15px] h-[15px]" />
          <p className="flex-1 min-w-[1px] relative text-ui-fg-subtle txt-compact-small-plus">
            Team
          </p>
        </div>
        <div className="flex gap-3 h-9 items-center overflow-clip px-2 py-1 relative rounded-md shrink-0 w-full z-[4]">
          <ChartPie className="w-[15px] h-[15px]" />
          <p className="flex-1 min-w-[1px] relative text-ui-fg-subtle txt-compact-small-plus">
            Reports
          </p>
        </div>
      </div>
      <div className="flex-1 min-h-[1px] relative w-full" />
      <div className="flex flex-col gap-0.5 p-3 relative shrink-0 w-full">
        <div className="flex gap-3 h-9 items-center overflow-clip px-2 py-1 relative rounded-md shrink-0 w-full">
          <CogSixTooth className="w-[15px] h-[15px]" />
          <p className="flex-1 min-w-[1px] relative text-ui-fg-subtle txt-compact-small-plus">
            Settings
          </p>
        </div>
      </div>
    </div>
  </div>
  <div className="bg-ui-border-base h-full relative shrink-0 w-px" />
</div>